# build
FROM node:20-alpine as build
WORKDIR /app
COPY . /app/
RUN npm install
RUN npm run build

# production
FROM node:20-alpine as production
ENV NODE_ENV production
WORKDIR /app
RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "$(pwd)" \
    --no-create-home \
    "api" && \
    chown -R api:api /app
USER api
COPY --from=build /app/node_modules /app/node_modules
COPY --from=build /app/dist /app/dist
COPY --from=build /app/package.json /app/package.json
CMD ["node", "./dist/main.js"]
EXPOSE 3000
