version: "3"
services:
  api:
    build:
      context: ./api
      dockerfile: ../dockerfile-api
    container_name: api
    ports:
      - "3000:3000"

  app:
    build:
      context: ./app
      dockerfile: ../dockerfile-app
    container_name: app
    ports:
      - "4200:4200"
